stages:
  - test-e2e
  - report

automation-e2e:
  stage: test-e2e
  image: ruby:2.5
   
  script:
  - apt-get update && apt-get install --quiet --assume-yes python-dev python-pip unzip wget
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - apt update
  - apt install -y google-chrome-stable
  - pip install robotframework 
  - pip install robotframework-seleniumlibrary
  - pip install robotframework-extendedrequestslibrary
  - pip install robotframework-faker 
  - pip install requests
  - pip install requests pytest
  - CHROMEDRIVER_VERSION=`wget --no-verbose --output-document - https://chromedriver.storage.googleapis.com/LATEST_RELEASE_106`
  - wget --no-verbose --output-document /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
  - unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver
  - chmod +x /opt/chromedriver/chromedriver
  - ln -fs /opt/chromedriver/chromedriver /usr/local/bin/chromedriver
  
  - robot -v BROWSER:HeadlessChrome -d ./results ./tests

  after_script:
    - cd ./results
    - mv report.html index.html

  
  artifacts:
    when: always
    paths:
      - ./results
    expire_in: 1 week
  tags:
    - linux
    - docker-runner

pages:
  stage: report
  when: always
  dependencies:
    - automation-e2e
  script:
    - mv results/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days

  tags:
    - linux
    - docker-runner
